version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ollama_data:/root/.ollama

  agent:
    build: ./agent
    container_name: agent
    restart: unless-stopped
    depends_on:
      - ollama
      - fuseki
    networks:
      - internal
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL = llama3
      - OLLAMA_EMBED_MODEL=nomic-embed-text
      - SPARQL_QUERY_URL=http://fuseki:3030/ds/sparql
      - SPARQL_UPDATE_URL=http://fuseki:3030/ds/update
      - SPARQL_DATA_URL=http://fuseki:3030/ds/data
      - READ_ONLY=true
    ports:
      - "8080:8080" 
    
  fuseki:
    image: stain/jena-fuseki:4.10.0
    container_name: fuseki
    restart: unless-stopped
    environment:
      - FUSEKI_DATASET=ds          # dataset name -> /ds/*
      - ADMIN_PASSWORD=admin       # change this in prod
    ports:
      - "3030:3030"                # expose UI + SPARQL to host (optional in prod)
    volumes:
      - fuseki_data:/fuseki        # persistent TDB2 storage
    networks: [internal]

      
networks:
  internal:
    driver: bridge

volumes:
  ollama_data:
  fuseki_data:
